# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2025-2026 Eli2
name: Build
on:
  push:
    branches:
      - master
jobs:
  build-linux:
    runs-on: codeberg-medium
    container:
      image: ubuntu:25.10
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: prepare
      run: |
        apt update -y --fix-missing
      env:
        DEBIAN_FRONTEND: noninteractive
    - name: install
      run: |
        bash .forgejo/workflows/install_debian_deps.sh
      env:
        DEBIAN_FRONTEND: noninteractive
    - name: configure
      run: |
        cmake --version
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
    - name: build
      run: |
        cmake --build build --target all
    - name: test
      run: |
        ctest --test-dir build
